[package]
name = "rust-blocks"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
parity-scale-codec = { version = "3.7.5", features = ["derive", "bit-vec"] }
subxt = "0.43.0"
tokio = { version = "1.46.1", features = ["rt", "rt-multi-thread"] }
